http:
  user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
  request_limit_per_min: 300

objects:
  chunk_size: 50

db:
  path: data.sqlite3
